management:
  endpoints:
    web:
      exposure:
        include: beans, health, info
  custom-settings:
    mode: prod
    owner: tom
    timeout: "5000"
logging:
  level:
    # ✅ 自作クラス（filter, interceptorなど）
    com.example.demo.filter: DEBUG
    com.example.demo.interceptor: DEBUG

    # ✅ Spring の標準 Filter 系
    org.springframework.web.filter: DEBUG

    # ✅ DispatcherServlet の動き（どのハンドラが選ばれたか）
    org.springframework.web.servlet.DispatcherServlet: DEBUG

    # ✅ HandlerMapping / Interceptor の流れ
    org.springframework.web.servlet.handler: DEBUG

    # ✅ リクエスト全般（Controllerの呼び出しなど）
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
app:
  s3:
    bucket: demo-bucket

aws:
  region: ap-northeast-1
  endpoint: http://localhost:4566
  accessKeyId: test
  secretAccessKey: test

grpc:
  greeter:
    host: 127.0.0.1 # Dockerネットワーク名やホストに合わせて: localhost / 127.0.0.1 / 実IP
    port: 50051
    plaintext: true # server_2 が TLS なしなら true
    deadlineMs: 0 # デッドライン（タイムアウト）ms

sample:
  name: "demo Application"
